//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NINA.Plugins.PolarAlignment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double DefaultMoveRate {
            get {
                return ((double)(this["DefaultMoveRate"]));
            }
            set {
                this["DefaultMoveRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultEastDirection {
            get {
                return ((bool)(this["DefaultEastDirection"]));
            }
            set {
                this["DefaultEastDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultTargetDistance {
            get {
                return ((int)(this["DefaultTargetDistance"]));
            }
            set {
                this["DefaultTargetDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double DefaultSearchRadius {
            get {
                return ((double)(this["DefaultSearchRadius"]));
            }
            set {
                this["DefaultSearchRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double DefaultAltitudeOffset {
            get {
                return ((double)(this["DefaultAltitudeOffset"]));
            }
            set {
                this["DefaultAltitudeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double DefaultAzimuthOffset {
            get {
                return ((double)(this["DefaultAzimuthOffset"]));
            }
            set {
                this["DefaultAzimuthOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color AltitudeErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AltitudeErrorColor"]));
            }
            set {
                this["AltitudeErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FFFF")]
        public global::System.Windows.Media.Color AzimuthErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["AzimuthErrorColor"]));
            }
            set {
                this["AzimuthErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color TotalErrorColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TotalErrorColor"]));
            }
            set {
                this["TotalErrorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0099")]
        public global::System.Windows.Media.Color TargetCircleColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TargetCircleColor"]));
            }
            set {
                this["TargetCircleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double MoveTimeoutFactor {
            get {
                return ((double)(this["MoveTimeoutFactor"]));
            }
            set {
                this["MoveTimeoutFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF32CD32")]
        public global::System.Windows.Media.Color SuccessColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SuccessColor"]));
            }
            set {
                this["SuccessColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogError {
            get {
                return ((bool)(this["LogError"]));
            }
            set {
                this["LogError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefractionAdjustment {
            get {
                return ((bool)(this["RefractionAdjustment"]));
            }
            set {
                this["RefractionAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseContinuousErrorEstimator {
            get {
                return ((bool)(this["UseContinuousErrorEstimator"]));
            }
            set {
                this["UseContinuousErrorEstimator"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AlignmentTolerance {
            get {
                return ((double)(this["AlignmentTolerance"]));
            }
            set {
                this["AlignmentTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StopTrackingWhenDone {
            get {
                return ((bool)(this["StopTrackingWhenDone"]));
            }
            set {
                this["StopTrackingWhenDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAvalonPolarAlignmentSystem {
            get {
                return ((bool)(this["UseAvalonPolarAlignmentSystem"]));
            }
            set {
                this["UseAvalonPolarAlignmentSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float AvalonXGearRatio {
            get {
                return ((float)(this["AvalonXGearRatio"]));
            }
            set {
                this["AvalonXGearRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int AvalonXSpeed {
            get {
                return ((int)(this["AvalonXSpeed"]));
            }
            set {
                this["AvalonXSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public float AvalonYGearRatio {
            get {
                return ((float)(this["AvalonYGearRatio"]));
            }
            set {
                this["AvalonYGearRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int AvalonYSpeed {
            get {
                return ((int)(this["AvalonYSpeed"]));
            }
            set {
                this["AvalonYSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoAutomatedAdjustments {
            get {
                return ((bool)(this["DoAutomatedAdjustments"]));
            }
            set {
                this["DoAutomatedAdjustments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double AutomatedAdjustmentSettleTime {
            get {
                return ((double)(this["AutomatedAdjustmentSettleTime"]));
            }
            set {
                this["AutomatedAdjustmentSettleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AvalonXBacklashCompensation {
            get {
                return ((float)(this["AvalonXBacklashCompensation"]));
            }
            set {
                this["AvalonXBacklashCompensation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonReverseAzimuth {
            get {
                return ((bool)(this["AvalonReverseAzimuth"]));
            }
            set {
                this["AvalonReverseAzimuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonReverseAltitude {
            get {
                return ((bool)(this["AvalonReverseAltitude"]));
            }
            set {
                this["AvalonReverseAltitude"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AvalonRememberedAzimuthResponsePerUnit {
            get {
                return ((double)(this["AvalonRememberedAzimuthResponsePerUnit"]));
            }
            set {
                this["AvalonRememberedAzimuthResponsePerUnit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonRememberedAzimuthResponseReverseAzimuth {
            get {
                return ((bool)(this["AvalonRememberedAzimuthResponseReverseAzimuth"]));
            }
            set {
                this["AvalonRememberedAzimuthResponseReverseAzimuth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonPreSeatAzimuthBeforeMeasurement {
            get {
                return ((bool)(this["AvalonPreSeatAzimuthBeforeMeasurement"]));
            }
            set {
                this["AvalonPreSeatAzimuthBeforeMeasurement"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double AvalonAzimuthPreSeatUnits {
            get {
                return ((double)(this["AvalonAzimuthPreSeatUnits"]));
            }
            set {
                this["AvalonAzimuthPreSeatUnits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AvalonAzimuthPreSeatDirection {
            get {
                return ((int)(this["AvalonAzimuthPreSeatDirection"]));
            }
            set {
                this["AvalonAzimuthPreSeatDirection"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonAzimuthTravelGuardEnabled {
            get {
                return ((bool)(this["AvalonAzimuthTravelGuardEnabled"]));
            }
            set {
                this["AvalonAzimuthTravelGuardEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonAzimuthTravelGuardConfirmed {
            get {
                return ((bool)(this["AvalonAzimuthTravelGuardConfirmed"]));
            }
            set {
                this["AvalonAzimuthTravelGuardConfirmed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequireExternalUpasSupervisorForAutomatedMoves {
            get {
                return ((bool)(this["RequireExternalUpasSupervisorForAutomatedMoves"]));
            }
            set {
                this["RequireExternalUpasSupervisorForAutomatedMoves"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://127.0.0.1:8443/")]
        public string UpasSupervisorEndpoint {
            get {
                return ((string)(this["UpasSupervisorEndpoint"]));
            }
            set {
                this["UpasSupervisorEndpoint"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double AvalonAzimuthTravelLimitDegrees {
            get {
                return ((double)(this["AvalonAzimuthTravelLimitDegrees"]));
            }
            set {
                this["AvalonAzimuthTravelLimitDegrees"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.025")]
        public double AvalonAzimuthDegreesPerNudgeUnit {
            get {
                return ((double)(this["AvalonAzimuthDegreesPerNudgeUnit"]));
            }
            set {
                this["AvalonAzimuthDegreesPerNudgeUnit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonAltitudeTravelGuardEnabled {
            get {
                return ((bool)(this["AvalonAltitudeTravelGuardEnabled"]));
            }
            set {
                this["AvalonAltitudeTravelGuardEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvalonAltitudeTravelGuardConfirmed {
            get {
                return ((bool)(this["AvalonAltitudeTravelGuardConfirmed"]));
            }
            set {
                this["AvalonAltitudeTravelGuardConfirmed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AvalonAltitudeStartingPositionDegrees {
            get {
                return ((double)(this["AvalonAltitudeStartingPositionDegrees"]));
            }
            set {
                this["AvalonAltitudeStartingPositionDegrees"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public double AvalonAltitudeMinimumDegrees {
            get {
                return ((double)(this["AvalonAltitudeMinimumDegrees"]));
            }
            set {
                this["AvalonAltitudeMinimumDegrees"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double AvalonAltitudeMaximumDegrees {
            get {
                return ((double)(this["AvalonAltitudeMaximumDegrees"]));
            }
            set {
                this["AvalonAltitudeMaximumDegrees"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.022")]
        public double AvalonAltitudeDegreesPerNudgeUnit {
            get {
                return ((double)(this["AvalonAltitudeDegreesPerNudgeUnit"]));
            }
            set {
                this["AvalonAltitudeDegreesPerNudgeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPause {
            get {
                return ((bool)(this["AutoPause"]));
            }
            set {
                this["AutoPause"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOAPAPolarAlignmentSystem {
            get {
                return ((bool)(this["UseOAPAPolarAlignmentSystem"]));
            }
            set {
                this["UseOAPAPolarAlignmentSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string SelectedPolarAlignmentSystem {
            get {
                return ((string)(this["SelectedPolarAlignmentSystem"]));
            }
            set {
                this["SelectedPolarAlignmentSystem"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float OAPAXGearRatio {
            get {
                return ((float)(this["OAPAXGearRatio"]));
            }
            set {
                this["OAPAXGearRatio"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int OAPAXSpeed {
            get {
                return ((int)(this["OAPAXSpeed"]));
            }
            set {
                this["OAPAXSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float OAPAYGearRatio {
            get {
                return ((float)(this["OAPAYGearRatio"]));
            }
            set {
                this["OAPAYGearRatio"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int OAPAYSpeed {
            get {
                return ((int)(this["OAPAYSpeed"]));
            }
            set {
                this["OAPAYSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float OAPAXBacklashCompensation {
            get {
                return ((float)(this["OAPAXBacklashCompensation"]));
            }
            set {
                this["OAPAXBacklashCompensation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OAPAReverseAzimuth {
            get {
                return ((bool)(this["OAPAReverseAzimuth"]));
            }
            set {
                this["OAPAReverseAzimuth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OAPAReverseAltitude {
            get {
                return ((bool)(this["OAPAReverseAltitude"]));
            }
            set {
                this["OAPAReverseAltitude"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int OAPAXRunCurrent {
            get {
                return ((int)(this["OAPAXRunCurrent"]));
            }
            set {
                this["OAPAXRunCurrent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int OAPAYRunCurrent {
            get {
                return ((int)(this["OAPAYRunCurrent"]));
            }
            set {
                this["OAPAYRunCurrent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int OAPAXHoldPercent {
            get {
                return ((int)(this["OAPAXHoldPercent"]));
            }
            set {
                this["OAPAXHoldPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int OAPAYHoldPercent {
            get {
                return ((int)(this["OAPAYHoldPercent"]));
            }
            set {
                this["OAPAYHoldPercent"] = value;
            }
        }
    }
}
